site_name: Alfredo-Project
theme:
  features:
    - content.code.copy
  logo: img/devil.jpg
  name: material
  palette:
    primary: Pink

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Luciferpaw/Alfredo-mkdocs
      
markdown_extensions:
    - attr_list
