site_name: Alfredo-Project
theme:
  features:
    plugins:
    - content.code.copy
  logo: img/img.png
  name: material
  palette:
    primary: Pink

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Luciferpaw/Alfredo-mkdocs